name: Build and tests

on:
  push:
    branches:
      - master

jobs:
  static-analysis:
    name: Run Static Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration Release

      - name: Upload analysis report (optional)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: static-analysis-report
          path: ./path-to-report

      - name: Run Docker Compose
        run: |
          cd TestUtilities/DockerFiles && docker-compose up --scale chrome=3 --scale edge=3 -d
        shell: bash
